### ISSUE TITLE
ModuleNotFoundError: No module named 'DQViT_new'

### ISSUE THREAD

**Issue by chouheiwa** [chenziwenhaoshuai/Vision-KAN#5]
The full traceback is:
```
Traceback (most recent call last):
  File "/home/chouheiwa/machine_learning/image_segmentation/Vision-KAN/main.py", line 15, in <module>
    from models_kan import create_model
  File "/home/chouheiwa/machine_learning/image_segmentation/Vision-KAN/models_kan.py", line 10, in <module>
    from DQViT_new import ViT as DQViT
ModuleNotFoundError: No module named 'DQViT_new'
```
And I think is we missed `DQViT_new`.

**Comment by chenziwenhaoshuai** [comment]
I am running multiple projects at the same time in the DeiT framework, I apologize for not removing extraneous code, I will fix it today!

**Comment by chenziwenhaoshuai** [comment]
I have removed the code related to DQViT.
